name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    # 1. Récupérer le code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Préparer Java (Nécessaire pour compiler avant Docker)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Compiler le projet (Pour créer le .jar)
    - name: Build with Maven
      # AJOUT CRITIQUE : On va dans le dossier avant de compiler
      working-directory: ./demo-github
      run: mvn clean package -DskipTests

    # 4. Login Docker Hub (Source: 41-45)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Build & Push (Source: 46-49)
    - name: Build & Push Docker image
      run: |
        cd demo-github
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
